name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  # JOB 1: Global Authentication Setup
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - name: Run Global Setup
        run: npx playwright test --project=setup
      - name: Upload Auth States
        uses: actions/upload-artifact@v4
        with:
          name: auth-states
          path: .auth/
          retention-days: 1

  # JOB 2: Sharded Test Execution
  test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Sharding: Split tests into 2 machines, each running a diferent shard of tests
        shardIndex: [1, 2]
        shardTotal: [2]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Lint Check
        run: npm run lint
      - name: Download Auth States
        uses: actions/download-artifact@v4
        with:
          name: auth-states
          path: .auth/
      - name: Run Sharded Tests
        # Runs both Web regression guest & member for this specific shard
        run: >
          npx playwright test 
          --project=web-regression-guest 
          --project=web-regression-member 
          --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
      - name: Upload Shard Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.shardIndex }}
          path: playwright-report/

  # JOB 3: Merge reports from all shards and upload final report
  merge-reports:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Lint Check
        run: npm run lint
      - name: Download all shard reports
        uses: actions/download-artifact@v4
        with:
          path: all-reports
          pattern: playwright-report-*
          merge-multiple: true
      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-reports
      - name: Upload Final Report
        uses: actions/upload-artifact@v4
        with:
          name: final-playwright-report
          path: playwright-report/
